export const transactions = [
    {
      id: "#CM9801",
      user: "Arjun Sharma",
      userAvatar: "https://example.com/avatars/arjun.jpg",
      project: "Landing Page",
      amount: 1500.0,
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "#CM9802",
      user: "Meera Nair",
      userAvatar: "https://example.com/avatars/meera.jpg",
      project: "CRM Admin pages",
      amount: 3200.5,
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "#CM9803",
      user: "Rohit Kumar",
      userAvatar: "https://example.com/avatars/rohit.jpg",
      project: "Client Project",
      amount: 850.75,
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "#CM9804",
      user: "Priya Iyer",
      userAvatar: "https://example.com/avatars/priya.jpg",
      project: "Admin Dashboard",
      amount: 2750.0,
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "#CM9805",
      user: "Suresh Reddy",
      userAvatar: "https://example.com/avatars/suresh.jpg",
      project: "App Landing Page",
      amount: 1100.25,
      date: "Feb 2, 2024",
      status: "Rejected",
    },
    {
      id: "#CM9806",
      user: "Anjali Singh",
      userAvatar: "https://example.com/avatars/anjali.jpg",
      project: "Mobile App Development",
      amount: 5000.0,
      date: "Feb 1, 2024",
      status: "In Progress",
    },
    {
      id: "#CM9807",
      user: "Ravi Menon",
      userAvatar: "https://example.com/avatars/ravi.jpg",
      project: "E-commerce Platform",
      amount: 4200.75,
      date: "Jan 31, 2024",
      status: "Complete",
    },
    {
      id: "#CM9808",
      user: "Lakshmi Pillai",
      userAvatar: "https://example.com/avatars/lakshmi.jpg",
      project: "SEO Optimization",
      amount: 950.5,
      date: "Jan 30, 2024",
      status: "Pending",
    },
    {
      id: "#CM9809",
      user: "Vikram Patel",
      userAvatar: "https://example.com/avatars/vikram.jpg",
      project: "Social Media Management",
      amount: 1250.0,
      date: "Jan 29, 2024",
      status: "Approved",
    },
    {
      id: "#CM9810",
      user: "Neha Joshi",
      userAvatar: "https://example.com/avatars/neha.jpg",
      project: "Content Writing",
      amount: 700.25,
      date: "Jan 28, 2024",
      status: "Complete",
    },
    {
      id: "#CM9811",
      user: "Amit Gupta",
      userAvatar: "https://example.com/avatars/amit.jpg",
      project: "Graphic Design",
      amount: 3400.0,
      date: "Jan 27, 2024",
      status: "In Progress",
    },
    {
      id: "#CM9812",
      user: "Kavya Ramesh",
      userAvatar: "https://example.com/avatars/kavya.jpg",
      project: "Web Development",
      amount: 5600.0,
      date: "Jan 26, 2024",
      status: "Rejected",
    },
    {
      id: "#CM9813",
      user: "Shivani Kapoor",
      userAvatar: "https://example.com/avatars/shivani.jpg",
      project: "App Development",
      amount: 4800.5,
      date: "Jan 25, 2024",
      status: "Approved",
    },
    {
      id: "#CM9814",
      user: "Manoj Desai",
      userAvatar: "https://example.com/avatars/manoj.jpg",
      project: "Email Marketing",
      amount: 2000.0,
      date: "Jan 24, 2024",
      status: "Pending",
    },
    {
      id: "#CM9815",
      user: "Ritu Verma",
      userAvatar: "https://example.com/avatars/ritu.jpg",
      project: "Branding",
      amount: 3300.75,
      date: "Jan 23, 2024",
      status: "Complete",
    },
    {
      id: "#CM9816",
      user: "Santosh Kulkarni",
      userAvatar: "https://example.com/avatars/santosh.jpg",
      project: "Market Research",
      amount: 2750.0,
      date: "Jan 22, 2024",
      status: "In Progress",
    },
    {
      id: "#CM9817",
      user: "Deepa Shetty",
      userAvatar: "https://example.com/avatars/deepa.jpg",
      project: "UI/UX Design",
      amount: 6000.0,
      date: "Jan 21, 2024",
      status: "Approved",
    },
    {
      id: "#CM9818",
      user: "Rajesh Malhotra",
      userAvatar: "https://example.com/avatars/rajesh.jpg",
      project: "Video Production",
      amount: 8200.5,
      date: "Jan 20, 2024",
      status: "Complete",
    },
    {
      id: "#CM9819",
      user: "Pooja Deshmukh",
      userAvatar: "https://example.com/avatars/pooja.jpg",
      project: "Photography",
      amount: 2400.0,
      date: "Jan 19, 2024",
      status: "Rejected",
    },
    {
      id: "#CM9820",
      user: "Karthik Krishnan",
      userAvatar: "https://example.com/avatars/karthik.jpg",
      project: "Digital Marketing",
      amount: 4100.75,
      date: "Jan 18, 2024",
      status: "Pending",
    },
  ];